### PR TITLE
Revert "dist: Remove support for building and distributing *.egg files"

### PR DESCRIPTION
**Pull request by jcfr**
This reverts commit dd239fd9aa4ed1c1dfb7f21d2b8952b9ac4ebb90.

### CODE REVIEW

**Comment by jcfr** [comment]
cc: @eeaston

**Comment by jcfr** [comment]
Dear project maintainers,

Would be awesome to move forward with integrating this PR and do a new release of the plugins on pypi :smile: 

Let me know if there is anything I could to help, 

Thanks,

**Comment by bmoscon** [comment]
@eeaston looks good to merge to me, does this work for the eggs you needed built?

**Comment by jcfr** [comment]
Thanks for merging :pray:

**Comment by eeaston** [comment]
No problems - very sorry for the massive delay on these! I'm running through all the PRs and getting a release out asap.

**Comment by jcfr** [comment]
Sounds good. And thanks for getting to it, I just did my due diligence of pinging the issue few days ago :smile:

**Pull request merged**
