### PR TITLE
Fix #44 - don't try to bind a random port.

### LINKED ISSUE #44: Hanging indefinitely on `s.bind` in base.py
Using 1.2.5, when I run my tests, the library hangs indefinitely on s.bind. I rolled back to 1.2.4 and it works. I'm fairly sure what's happening is that binding to a random IP doesn't work on OSX.
https://github.com/manahl/pytest-plugins/blob/master/pytest-server-fixtures/pytest_server_fixtures/base.py#L43

### PR DESCRIPTION
**Pull request by Daenyth**
This hangs indefinitely on macOS for an unknown reason.

I confirmed that this fix works for me on my machine

### CODE REVIEW

**Comment by Daenyth** [comment]
It seems like every loopback address needs to be individually enabled on macOS - https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x

**Comment by bmoscon** [comment]
@eeaston

**Comment by bmoscon** [comment]
Let me try pinging @eeaston one more time, then I'll merge it

**Comment by eeaston** [comment]
Hi there, sorry for the delay in getting back to you guys!
So this (rather odd-looking I agree) behaviour is there for a reason - on high-volume build slaves running a lot of parallel tests we were seeing port clashes even using the kernel ephemeral port method to 127.0.01. It's unlikely, as the requests have to come in within like, 0.1 seconds, but it's non-zero.
Can we update the PR to keep the existing behaviour and fall-back to 127.0.0.1 for OSX where it's generally unavailable?

**Comment by Daenyth** [comment]
Yes, I'll update it to do that and leave a comment why

**Comment by bmoscon** [comment]
@Daenyth thanks! Not sure if you've had a chance to do this or not, but I could handle the addition of the case code to switch between OSX/linux if you dont have any free time.

**Comment by Daenyth** [comment]
Yes I'd definitely appreciate that. I think I set this PR where you can
commit to the source branch. Go for it

**Comment by bmoscon** [comment]
@eeaston @Daenyth I've updated the code (thanks @Daenyth for letting me commit to your branch). let me know what you think

**Comment by Daenyth** [comment]
:shipit:

**Comment by bmoscon** [comment]
@eeaston you ok with this last change? I'm really itching to merge this - I've been doing more and more development on my mac and I keep hitting this on arctic

**Comment by eeaston** [comment]
LGTM, thanks guys

**Comment by bmoscon** [comment]
@eeaston can we roll a new release with these changes?

**Pull request merged**
