### PR TITLE
allow installation from source using pip

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by bmoscon** [comment]
I don't see any issues with this, but I'll leave it to @eeaston to merge it.

**Comment by xoviat** [comment]
I still need to add some checks in common setup

**Comment by xoviat** [comment]
alright, that appears to work!

**Comment by eeaston** [comment]
Hiya - many thanks for this!
I don't mean to be pedantic but most of the changes in this PR seem to be whitespace related. Can we try and cut the changes down to just what's needed? Thanks :)

**Comment by xoviat** [comment]
@eeaston Done. For the record, yapf made the formatting changes.

**Comment by eeaston** [comment]
Great, thanks!

**Pull request merged**
