### PR TITLE
Test against Python 3.7 and support pytest 4.x

### PR DESCRIPTION
**Pull request by jcfr**
This PR adds support for Python 3.7 and will be updated to address #100, #110, #92 , #125

### CODE REVIEW

**Comment by jcfr** [comment]
For reference, setting `COVERALLS_REPO_TOKEN` is required to use `coveralls` python client or to submit coverage results using `curl`. Failing to do so reports `Couldn't find a repository matching this job`.
See https://github.com/lemurheavy/coveralls-public/issues/487 and https://github.com/z4r/python-coveralls#configuration

**Comment by jcfr** [comment]
@bmoscon @eeaston @javefang  This is now ready for final review.  

It addresses issues #125 #122 #110 and #100

After getting your feedback, I will also:
* [ ] update [CHANGES.md](https://github.com/manahl/pytest-plugins/blob/master/CHANGES.md)
* [ ] update the `install_all` target in the `Makefile` so that python 3.7 is also installed in [Vagrantfile](https://github.com/manahl/pytest-plugins/blob/master/Vagrantfile)

Once, this is done it would be great to cut a release and have all the wheels uploaded to pypi. This will all me to fix testing associated with [cmake-python-distributions](https://github.com/scikit-build/cmake-python-distributions), [ninja-python-distributions](https://github.com/scikit-build/ninja-python-distributions) and [scikit-build](https://github.com/scikit-build/scikit-build)

Cc: @thewtex

**Comment by bmoscon** [comment]
@eeaston @javefang looks good to me, but given the size and scope of the change I'd like to have another review before merging

**Comment by jcfr** [comment]
Et voila. The last two updates have been pushed. Now looking forward final reviews.

In the mean time and waiting new official wheels are released, temporary ones are available at https://github.com/jcfr/pytest-plugins/releases/tag/v1.7.0.dev15

They can be installed using:

```
pip install pytest-virtualenv -f https://github.com/jcfr/pytest-plugins/releases/tag/v1.7.0.dev15 --pre
```

**Comment by javefang** [comment]
LGTM, thanks for the contribution!
@eeaston , I tested the branch against pytest==3.1.0 which is also a pass.

**Comment by ssbarnea** [comment]
When can have this merged as now I went into conflicts caused by:
```
pytest-verbose-parametrize 1.5.1 has requirement pytest<4.0.0, but you have pytest 4.3.1.
```

**Comment by jcfr** [comment]
@ssbarnea As a temporary workaround, you could install corresponding development wheels. See https://github.com/manahl/pytest-plugins/pull/130#issuecomment-471149935

**Comment by ssbarnea** [comment]
@jcfr Thanks for the hint but I will have to pass. I would not be able to do this even if the pre-release would be on posted on pypi as we have a policy of not using unreleased dependencies (not a real surproise). 

For the moment I added a <4.0.0 on pytest with a comment blaming pytest-verbose-parametrize as being the reason.

**Comment by bmoscon** [comment]
@eeaston this ok to merge? I'll probably squash and merge it soon unless you want to review/comment

**Comment by jcfr** [comment]
For convenience, here is a squashed version of that same topic:

**Comment by eeaston** [comment]
Hi guys apologies for the tardy replies.
@jcfr  - amazing PR, many thanks for the hard work, I'll start going through it.

**Comment by eeaston** [comment]
LGTM, many thanks! I'll approve the squashed PR #134

**Comment by jcfr** [comment]
> I'll approve the squashed PR #134

Closing this one.

**Pull request closed without merging**
